/*
 * examples.js — Bibliothèque de circuits d'exemples.
 *
 * Chaque exemple est un document complet (composants + fils + cartouche),
 * prêt à charger et à simuler. Les topologies sont vérifiées par les tests
 * de simulation (mêmes coordonnées que les circuits de validation).
 */

const EXAMPLES = [
  {
    id: 'lamp',
    name: 'Lampe + interrupteur',
    level: 'Débutant',
    sim: 'dc', simLabel: 'Simulation DC',
    desc: 'Le circuit de base : pile, interrupteur, lampe. Double-clique l’interrupteur pour le fermer, puis lance la simulation continue.',
    data: {
      version: 1,
      meta: { title: 'Lampe + interrupteur', author: 'Exemples ÉlectriCAD' },
      counters: { BT: 1, SW: 1, LA: 1, GND: 1 },
      components: [
        { id: 'BT1', type: 'battery', x: 100, y: 200, rot: 0, label: 'BT1', value: '4.5 V' },
        { id: 'SW1', type: 'switch', x: 260, y: 100, rot: 0, label: 'SW1', value: '', closed: false },
        { id: 'LA1', type: 'lamp', x: 420, y: 200, rot: 90, label: 'LA1', value: '' },
        { id: 'GND1', type: 'ground', x: 280, y: 300, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: 60, y: 200 }, { x: 60, y: 100 }, { x: 220, y: 100 }] },
        { id: 'w2', points: [{ x: 300, y: 100 }, { x: 420, y: 100 }, { x: 420, y: 160 }] },
        { id: 'w3', points: [{ x: 420, y: 240 }, { x: 420, y: 300 }, { x: 140, y: 300 }, { x: 140, y: 200 }] },
        { id: 'w4', points: [{ x: 280, y: 280 }, { x: 280, y: 300 }] },
      ],
    },
  },
  {
    id: 'divider',
    name: 'Diviseur de tension',
    level: 'Débutant',
    sim: 'dc', simLabel: 'Simulation DC',
    desc: 'Deux résistances en série divisent la tension : 9 V → 4,5 V au point milieu. Le grand classique. Lance la simulation continue.',
    data: {
      version: 1,
      meta: { title: 'Diviseur de tension', author: 'Exemples ÉlectriCAD' },
      counters: { V: 1, R: 2, GND: 1 },
      components: [
        { id: 'V1', type: 'dc_source', x: 200, y: 200, rot: 0, label: 'V1', value: '9 V' },
        { id: 'R1', type: 'resistor', x: 200, y: 100, rot: 90, label: 'R1', value: '1k' },
        { id: 'R2', type: 'resistor', x: 200, y: 300, rot: 90, label: 'R2', value: '1k' },
        { id: 'GND1', type: 'ground', x: 360, y: 360, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: 160, y: 200 }, { x: 160, y: 60 }, { x: 200, y: 60 }] },
        { id: 'w2', points: [{ x: 200, y: 140 }, { x: 200, y: 260 }] },
        { id: 'w3', points: [{ x: 200, y: 340 }, { x: 240, y: 340 }, { x: 240, y: 200 }] },
        { id: 'w4', points: [{ x: 360, y: 340 }, { x: 200, y: 340 }] },
      ],
    },
  },
  {
    id: 'led',
    name: 'LED + résistance',
    level: 'Débutant',
    sim: 'dc', simLabel: 'Simulation DC',
    desc: 'Alimenter une LED sans la griller : la résistance de 330 Ω limite le courant à ~10 mA. Simulation non linéaire (Vf ≈ 1,8 V).',
    data: {
      version: 1,
      meta: { title: 'LED + résistance série', author: 'Exemples ÉlectriCAD' },
      counters: { V: 1, R: 1, D: 1, GND: 1 },
      components: [
        { id: 'V1', type: 'dc_source', x: 0, y: 0, rot: 0, label: 'V1', value: '5 V' },
        { id: 'R1', type: 'resistor', x: 200, y: 0, rot: 0, label: 'R1', value: '330' },
        { id: 'D1', type: 'led', x: 400, y: 100, rot: 90, label: 'D1', value: '' },
        { id: 'GND1', type: 'ground', x: 500, y: 200, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: -40, y: 0 }, { x: -40, y: -60 }, { x: 160, y: -60 }, { x: 160, y: 0 }] },
        { id: 'w2', points: [{ x: 240, y: 0 }, { x: 400, y: 0 }, { x: 400, y: 60 }] },
        { id: 'w3', points: [{ x: 400, y: 140 }, { x: 400, y: 200 }, { x: 500, y: 200 }, { x: 500, y: 180 }] },
        { id: 'w4', points: [{ x: 40, y: 0 }, { x: 40, y: 200 }, { x: 500, y: 200 }] },
      ],
    },
  },
  {
    id: 'rc',
    name: 'Charge d’un condensateur',
    level: 'Intermédiaire',
    sim: 'trans', simLabel: 'Transitoire',
    desc: 'Circuit RC : le condensateur se charge exponentiellement (τ = RC = 1 ms). Lance l’analyse transitoire sur ~5 ms pour voir la courbe.',
    data: {
      version: 1,
      meta: { title: 'Charge RC (τ = 1 ms)', author: 'Exemples ÉlectriCAD' },
      counters: { V: 1, R: 1, C: 1, GND: 1 },
      components: [
        { id: 'V1', type: 'dc_source', x: 0, y: 0, rot: 0, label: 'V1', value: '5 V' },
        { id: 'R1', type: 'resistor', x: 200, y: 0, rot: 0, label: 'R1', value: '1k' },
        { id: 'C1', type: 'capacitor', x: 400, y: 100, rot: 90, label: 'C1', value: '1u' },
        { id: 'GND1', type: 'ground', x: 500, y: 200, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: -40, y: 0 }, { x: -40, y: -60 }, { x: 160, y: -60 }, { x: 160, y: 0 }] },
        { id: 'w2', points: [{ x: 240, y: 0 }, { x: 400, y: 0 }, { x: 400, y: 60 }] },
        { id: 'w3', points: [{ x: 400, y: 140 }, { x: 400, y: 200 }, { x: 500, y: 200 }, { x: 500, y: 180 }] },
        { id: 'w4', points: [{ x: 40, y: 0 }, { x: 40, y: 200 }, { x: 500, y: 200 }] },
      ],
    },
  },
  {
    id: 'lowpass',
    name: 'Filtre passe-bas RC',
    level: 'Intermédiaire',
    sim: 'bode', simLabel: 'Bode',
    desc: 'Filtre du 1er ordre, fc = 159 Hz. Lance l’analyse Bode : −3 dB et −45° à la fréquence de coupure, pente −20 dB/décade.',
    data: {
      version: 1,
      meta: { title: 'Filtre passe-bas RC (fc = 159 Hz)', author: 'Exemples ÉlectriCAD' },
      counters: { V: 1, R: 1, C: 1, GND: 1 },
      components: [
        { id: 'AC1', type: 'ac_source', x: 0, y: 0, rot: 0, label: 'V1', value: '1' },
        { id: 'R1', type: 'resistor', x: 200, y: 0, rot: 0, label: 'R1', value: '1k' },
        { id: 'C1', type: 'capacitor', x: 400, y: 100, rot: 90, label: 'C1', value: '1u' },
        { id: 'GND1', type: 'ground', x: 500, y: 200, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: -40, y: 0 }, { x: -40, y: -60 }, { x: 160, y: -60 }, { x: 160, y: 0 }] },
        { id: 'w2', points: [{ x: 240, y: 0 }, { x: 400, y: 0 }, { x: 400, y: 60 }] },
        { id: 'w3', points: [{ x: 400, y: 140 }, { x: 400, y: 200 }, { x: 500, y: 200 }, { x: 500, y: 180 }] },
        { id: 'w4', points: [{ x: 40, y: 0 }, { x: 40, y: 200 }, { x: 500, y: 200 }] },
      ],
    },
  },
  {
    id: 'rectifier',
    name: 'Redresseur à diode',
    level: 'Intermédiaire',
    sim: 'trans', simLabel: 'Transitoire',
    desc: 'Redressement mono-alternance : la diode ne laisse passer que les alternances positives. Analyse transitoire à 50 Hz sur 40 ms.',
    data: {
      version: 1,
      meta: { title: 'Redresseur mono-alternance', author: 'Exemples ÉlectriCAD' },
      counters: { V: 1, D: 1, R: 1, GND: 1 },
      components: [
        { id: 'AC1', type: 'ac_source', x: 0, y: 0, rot: 0, label: 'V1', value: '10' },
        { id: 'D1', type: 'diode', x: 200, y: 0, rot: 0, label: 'D1', value: '' },
        { id: 'R1', type: 'resistor', x: 400, y: 100, rot: 90, label: 'R1', value: '1k' },
        { id: 'GND1', type: 'ground', x: 500, y: 200, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: -40, y: 0 }, { x: -40, y: -60 }, { x: 160, y: -60 }, { x: 160, y: 0 }] },
        { id: 'w2', points: [{ x: 240, y: 0 }, { x: 400, y: 0 }, { x: 400, y: 60 }] },
        { id: 'w3', points: [{ x: 400, y: 140 }, { x: 400, y: 200 }, { x: 500, y: 200 }, { x: 500, y: 180 }] },
        { id: 'w4', points: [{ x: 40, y: 0 }, { x: 40, y: 200 }, { x: 500, y: 200 }] },
      ],
    },
  },
  {
    id: 'bjt',
    name: 'Transistor en commutation',
    level: 'Avancé',
    sim: 'dc', simLabel: 'Simulation DC',
    desc: 'Montage émetteur commun (β = 100) : le courant de base (43 µA) commande un courant de collecteur 100× plus grand. Simulation DC.',
    data: {
      version: 1,
      meta: { title: 'Transistor NPN — émetteur commun', author: 'Exemples ÉlectriCAD' },
      counters: { V: 1, R: 2, Q: 1, GND: 1 },
      components: [
        { id: 'V1', type: 'dc_source', x: 0, y: 100, rot: 0, label: 'V1', value: '5 V' },
        { id: 'Rb', type: 'resistor', x: 150, y: 40, rot: 0, label: 'R1', value: '100k' },
        { id: 'Rc', type: 'resistor', x: 150, y: 120, rot: 0, label: 'R2', value: '1k' },
        { id: 'Q1', type: 'transistor_npn', x: 300, y: 200, rot: 0, label: 'Q1', value: '100' },
        { id: 'GND1', type: 'ground', x: 40, y: 300, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: -40, y: 100 }, { x: -40, y: 40 }, { x: 110, y: 40 }] },
        { id: 'w2', points: [{ x: -40, y: 100 }, { x: -40, y: 120 }, { x: 110, y: 120 }] },
        { id: 'w3', points: [{ x: 190, y: 40 }, { x: 260, y: 40 }, { x: 260, y: 200 }] },
        { id: 'w4', points: [{ x: 190, y: 120 }, { x: 300, y: 120 }, { x: 300, y: 160 }] },
        { id: 'w5', points: [{ x: 40, y: 100 }, { x: 40, y: 280 }] },
        { id: 'w6', points: [{ x: 40, y: 280 }, { x: 300, y: 280 }, { x: 300, y: 240 }] },
      ],
    },
  },
  {
    id: 'halfadder',
    name: 'Demi-additionneur logique',
    level: 'Avancé',
    sim: 'logic', simLabel: 'Logique',
    desc: 'S = A ⊕ B (somme), C = A · B (retenue). Double-clique les entrées pour changer 0/1, puis lance la simulation logique.',
    data: {
      version: 1,
      meta: { title: 'Demi-additionneur (XOR + AND)', author: 'Exemples ÉlectriCAD' },
      counters: { IN: 2, U: 2, OUT: 2 },
      components: [
        { id: 'A', type: 'logic_in', x: 0, y: -60, rot: 0, label: 'A', value: '', high: true },
        { id: 'B', type: 'logic_in', x: 0, y: 140, rot: 0, label: 'B', value: '', high: false },
        { id: 'U1', type: 'gate_xor', x: 240, y: -40, rot: 0, label: 'U1', value: '' },
        { id: 'U2', type: 'gate_and', x: 240, y: 120, rot: 0, label: 'U2', value: '' },
        { id: 'S', type: 'logic_out', x: 400, y: -40, rot: 0, label: 'S', value: '' },
        { id: 'C', type: 'logic_out', x: 400, y: 120, rot: 0, label: 'C', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: 40, y: -60 }, { x: 200, y: -60 }] },
        { id: 'w2', points: [{ x: 100, y: -60 }, { x: 100, y: 100 }, { x: 200, y: 100 }] },
        { id: 'w3', points: [{ x: 40, y: 140 }, { x: 200, y: 140 }] },
        { id: 'w4', points: [{ x: 140, y: 140 }, { x: 140, y: -20 }, { x: 200, y: -20 }] },
        { id: 'w5', points: [{ x: 280, y: -40 }, { x: 360, y: -40 }] },
        { id: 'w6', points: [{ x: 280, y: 120 }, { x: 360, y: 120 }] },
      ],
    },
  },
  {
    id: 'tableau',
    name: 'Tableau électrique (NF C 15-100)',
    level: 'Avancé',
    sim: 'dc', simLabel: 'Simulation DC',
    desc: 'Arrivée 230 V → interrupteur différentiel 30 mA → 3 disjoncteurs : éclairage (va-et-vient), prise 2P+T, sonnerie. Ouvre/ferme les modules au double-clic.',
    data: {
      version: 1,
      meta: { title: 'Tableau électrique NF C 15-100', author: 'Exemples ÉlectriCAD' },
      counters: { V: 1, ID: 1, Q: 3, SW: 1, LA: 1, PC: 1, H: 1, GND: 1 },
      components: [
        { id: 'V1', type: 'dc_source', x: 0, y: 0, rot: 0, label: 'V1', value: '230' },
        { id: 'ID1', type: 'rcd', x: 180, y: -140, rot: 0, label: 'ID1', value: '', closed: true },
        { id: 'Q1', type: 'breaker', x: 360, y: -140, rot: 0, label: 'Q1', value: '', closed: true },
        { id: 'S1', type: 'sw_vv', x: 500, y: -140, rot: 0, label: 'S1', value: '', closed: false },
        { id: 'LA1', type: 'lamp', x: 660, y: -140, rot: 0, label: 'LA1', value: '' },
        { id: 'Q2', type: 'breaker', x: 360, y: -40, rot: 0, label: 'Q2', value: '', closed: true },
        { id: 'PC1', type: 'socket', x: 500, y: -40, rot: 0, label: 'PC1', value: '' },
        { id: 'Q3', type: 'breaker', x: 360, y: 60, rot: 0, label: 'Q3', value: '', closed: true },
        { id: 'H1', type: 'bell', x: 500, y: 60, rot: 0, label: 'H1', value: '' },
        { id: 'GND1', type: 'ground', x: 100, y: 220, rot: 0, label: '', value: '' },
      ],
      wires: [
        { id: 'wf', points: [{ x: -40, y: 0 }, { x: -40, y: -140 }, { x: 140, y: -140 }] },
        { id: 'wbus', points: [{ x: 220, y: -140 }, { x: 280, y: -140 }, { x: 280, y: 60 }] },
        { id: 'wr1', points: [{ x: 280, y: -140 }, { x: 320, y: -140 }] },
        { id: 'wr2', points: [{ x: 280, y: -40 }, { x: 320, y: -40 }] },
        { id: 'wr3', points: [{ x: 280, y: 60 }, { x: 320, y: 60 }] },
        { id: 'wvv', points: [{ x: 400, y: -140 }, { x: 460, y: -140 }] },
        { id: 'wl1', points: [{ x: 540, y: -160 }, { x: 580, y: -160 }, { x: 580, y: -140 }, { x: 620, y: -140 }] },
        { id: 'wlr', points: [{ x: 700, y: -140 }, { x: 760, y: -140 }] },
        { id: 'wpc1', points: [{ x: 400, y: -40 }, { x: 460, y: -40 }] },
        { id: 'wpc2', points: [{ x: 540, y: -40 }, { x: 760, y: -40 }] },
        { id: 'wh1', points: [{ x: 400, y: 60 }, { x: 460, y: 60 }] },
        { id: 'wh2', points: [{ x: 540, y: 60 }, { x: 760, y: 60 }] },
        { id: 'wn', points: [{ x: 760, y: -140 }, { x: 760, y: 180 }, { x: 40, y: 180 }, { x: 40, y: 0 }] },
        { id: 'wg', points: [{ x: 100, y: 200 }, { x: 100, y: 180 }] },
      ],
    },
  },
  {
    id: 'sevenseg',
    name: 'Afficheur 7 segments',
    level: 'Intermédiaire',
    sim: 'logic', simLabel: 'Logique',
    desc: 'Quatre bits (1-2-4-8) pilotent un afficheur 7 segments. Double-clique les entrées pour composer un chiffre, puis lance la simulation logique.',
    data: {
      version: 1,
      meta: { title: 'Afficheur 7 segments', author: 'Exemples ÉlectriCAD' },
      counters: { IN: 4, AFF: 1 },
      components: [
        { id: 'A', type: 'logic_in', x: 0, y: -90, rot: 0, label: 'b1', value: '', high: true },
        { id: 'B', type: 'logic_in', x: 0, y: -30, rot: 0, label: 'b2', value: '', high: false },
        { id: 'C', type: 'logic_in', x: 0, y: 30, rot: 0, label: 'b4', value: '', high: false },
        { id: 'D', type: 'logic_in', x: 0, y: 90, rot: 0, label: 'b8', value: '', high: true },
        { id: 'AFF1', type: 'seven_seg', x: 200, y: 0, rot: 0, label: 'AFF1', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: 40, y: -90 }, { x: 120, y: -90 }, { x: 120, y: -30 }, { x: 160, y: -30 }] },
        { id: 'w2', points: [{ x: 40, y: -30 }, { x: 100, y: -30 }, { x: 100, y: -10 }, { x: 160, y: -10 }] },
        { id: 'w3', points: [{ x: 40, y: 30 }, { x: 100, y: 30 }, { x: 100, y: 10 }, { x: 160, y: 10 }] },
        { id: 'w4', points: [{ x: 40, y: 90 }, { x: 120, y: 90 }, { x: 120, y: 30 }, { x: 160, y: 30 }] },
      ],
    },
  },
  {
    id: 'divfreq',
    name: 'Diviseur de fréquence',
    level: 'Avancé',
    sim: 'logic', simLabel: 'Logique',
    desc: 'Une bascule D rebouclée sur Q̄ divise la fréquence de l’horloge par 2 — la brique de base des compteurs. Observe le chronogramme.',
    data: {
      version: 1,
      meta: { title: 'Diviseur de fréquence (bascule D)', author: 'Exemples ÉlectriCAD' },
      counters: { CLK: 1, U: 1, OUT: 1 },
      components: [
        { id: 'CK', type: 'clock', x: 0, y: 0, rot: 0, label: 'CLK', value: '4' },
        { id: 'U1', type: 'dff', x: 240, y: 0, rot: 0, label: 'U1', value: '' },
        { id: 'S', type: 'logic_out', x: 400, y: -20, rot: 0, label: 'S', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: 40, y: 0 }, { x: 160, y: 0 }, { x: 160, y: 20 }, { x: 200, y: 20 }] },
        { id: 'w2', points: [{ x: 280, y: 20 }, { x: 320, y: 20 }, { x: 320, y: 60 }, { x: 120, y: 60 }, { x: 120, y: -20 }, { x: 200, y: -20 }] },
        { id: 'w3', points: [{ x: 280, y: -20 }, { x: 360, y: -20 }] },
      ],
    },
  },
  {
    id: 'counter',
    name: 'Compteur 2 bits',
    level: 'Avancé',
    sim: 'logic', simLabel: 'Logique',
    desc: 'Deux bascules D en cascade comptent les fronts de l’horloge : Q0 à f/2, Q1 à f/4 — les 4 états 00→01→10→11 au chronogramme.',
    data: {
      version: 1,
      meta: { title: 'Compteur binaire 2 bits', author: 'Exemples ÉlectriCAD' },
      counters: { CLK: 1, U: 2, OUT: 2 },
      components: [
        { id: 'CK', type: 'clock', x: 0, y: 0, rot: 0, label: 'CLK', value: '2' },
        { id: 'U1', type: 'dff', x: 240, y: 0, rot: 0, label: 'U1', value: '' },
        { id: 'U2', type: 'dff', x: 520, y: 0, rot: 0, label: 'U2', value: '' },
        { id: 'O0', type: 'logic_out', x: 400, y: -80, rot: 0, label: 'Q0', value: '' },
        { id: 'O1', type: 'logic_out', x: 680, y: -20, rot: 0, label: 'Q1', value: '' },
      ],
      wires: [
        { id: 'w1', points: [{ x: 40, y: 0 }, { x: 160, y: 0 }, { x: 160, y: 20 }, { x: 200, y: 20 }] },
        { id: 'w2', points: [{ x: 280, y: 20 }, { x: 320, y: 20 }, { x: 320, y: 60 }, { x: 120, y: 60 }, { x: 120, y: -20 }, { x: 200, y: -20 }] },
        { id: 'w3', points: [{ x: 320, y: 20 }, { x: 480, y: 20 }] },
        { id: 'w4', points: [{ x: 560, y: 20 }, { x: 600, y: 20 }, { x: 600, y: 60 }, { x: 400, y: 60 }, { x: 400, y: -20 }, { x: 480, y: -20 }] },
        { id: 'w5', points: [{ x: 280, y: -20 }, { x: 300, y: -20 }, { x: 300, y: -80 }, { x: 360, y: -80 }] },
        { id: 'w6', points: [{ x: 560, y: -20 }, { x: 640, y: -20 }] },
      ],
    },
  },
  {
    id: 'maison',
    name: 'Maison T2 — implantation élec.',
    level: 'Avancé',
    sim: 'plan', simLabel: 'Plan 2D / 3D',
    desc: 'Plan d’un T2 : murs, portes, fenêtres, mobilier — et l’installation NF C 15-100 : GTL + tableau, goulottes, prises, interrupteurs, DCL. Ouvre la vue 3D !',
    data: {
      version: 1,
      meta: { title: 'Maison T2 — implantation électrique', author: 'Exemples ÉlectriCAD' },
      counters: { TB: 1, GTL: 1, PC: 7, SW: 2, DCL: 2, BD: 2 },
      components: [
        // Architecture
        { id: 'p1', type: 'door', x: 100, y: 520, rot: 0, label: '', value: '' },
        { id: 'p2', type: 'door', x: 340, y: 260, rot: 90, label: '', value: '' },
        { id: 'f1', type: 'window_a', x: 170, y: 0, rot: 0, label: '', value: '' },
        { id: 'f2', type: 'window_a', x: 570, y: 0, rot: 0, label: '', value: '' },
        { id: 'f3', type: 'window_a', x: 800, y: 260, rot: 90, label: '', value: '' },
        // Mobilier
        { id: 'm1', type: 'bed', x: 150, y: 140, rot: 0, label: '', value: '' },
        { id: 'm2', type: 'wardrobe', x: 250, y: 480, rot: 0, label: '', value: '' },
        { id: 'm3', type: 'sofa', x: 480, y: 120, rot: 0, label: '', value: '' },
        { id: 'm4', type: 'table', x: 560, y: 350, rot: 0, label: '', value: '' },
        { id: 'm5', type: 'counter', x: 690, y: 60, rot: 0, label: '', value: '' },
        // Implantation électrique
        { id: 'TB1', type: 'panel_house', x: 46, y: 340, rot: 0, label: 'TB1', value: '' },
        { id: 'GTL1', type: 'gtl', x: 30, y: 430, rot: 0, label: 'GTL', value: '' },
        { id: 'PC1', type: 'socket_wall', x: 20, y: 150, rot: 90, label: 'PC1', value: '' },
        { id: 'PC2', type: 'socket_wall', x: 315, y: 80, rot: 270, label: 'PC2', value: '' },
        { id: 'PC3', type: 'socket_wall', x: 780, y: 150, rot: 270, label: 'PC3', value: '' },
        { id: 'PC4', type: 'socket_wall', x: 780, y: 400, rot: 270, label: 'PC4', value: '' },
        { id: 'PC5', type: 'socket_wall', x: 500, y: 500, rot: 0, label: 'PC5', value: '' },
        { id: 'PC6', type: 'socket_wall', x: 620, y: 20, rot: 180, label: 'PC6', value: '' },
        { id: 'PC7', type: 'socket_wall', x: 700, y: 20, rot: 180, label: 'PC7', value: '' },
        { id: 'SW1', type: 'switch_sa', x: 315, y: 320, rot: 0, label: 'SW1', value: '' },
        { id: 'SW2', type: 'switch_vv_wall', x: 170, y: 495, rot: 0, label: 'SW2', value: '' },
        { id: 'DCL1', type: 'dcl', x: 170, y: 240, rot: 0, label: 'DCL1', value: '' },
        { id: 'DCL2', type: 'dcl', x: 570, y: 240, rot: 0, label: 'DCL2', value: '' },
        { id: 'BD1', type: 'jbox', x: 170, y: 40, rot: 0, label: 'BD1', value: '' },
        { id: 'BD2', type: 'jbox', x: 570, y: 40, rot: 0, label: 'BD2', value: '' },
      ],
      wires: [
        // Murs
        { id: 'mu1', kind: 'wall', points: [{ x: 0, y: 0 }, { x: 800, y: 0 }] },
        { id: 'mu2', kind: 'wall', points: [{ x: 800, y: 0 }, { x: 800, y: 520 }] },
        { id: 'mu3', kind: 'wall', points: [{ x: 800, y: 520 }, { x: 140, y: 520 }] },
        { id: 'mu4', kind: 'wall', points: [{ x: 60, y: 520 }, { x: 0, y: 520 }] },
        { id: 'mu5', kind: 'wall', points: [{ x: 0, y: 520 }, { x: 0, y: 0 }] },
        { id: 'mu6', kind: 'wall', points: [{ x: 340, y: 0 }, { x: 340, y: 220 }] },
        { id: 'mu7', kind: 'wall', points: [{ x: 340, y: 300 }, { x: 340, y: 520 }] },
        // Goulottes / chemins de câbles
        { id: 'g1', kind: 'conduit', points: [{ x: 46, y: 340 }, { x: 30, y: 340 }, { x: 30, y: 430 }] },
        { id: 'g2', kind: 'conduit', points: [{ x: 30, y: 340 }, { x: 30, y: 150 }, { x: 20, y: 150 }] },
        { id: 'g3', kind: 'conduit', points: [{ x: 30, y: 150 }, { x: 30, y: 40 }, { x: 170, y: 40 }] },
        { id: 'g4', kind: 'conduit', points: [{ x: 170, y: 40 }, { x: 170, y: 240 }] },
        { id: 'g5', kind: 'conduit', points: [{ x: 170, y: 40 }, { x: 315, y: 40 }, { x: 315, y: 80 }] },
        { id: 'g6', kind: 'conduit', points: [{ x: 315, y: 80 }, { x: 315, y: 320 }] },
        { id: 'g7', kind: 'conduit', points: [{ x: 46, y: 340 }, { x: 46, y: 460 }, { x: 170, y: 460 }, { x: 170, y: 495 }] },
        { id: 'g8', kind: 'conduit', points: [{ x: 170, y: 460 }, { x: 500, y: 460 }, { x: 500, y: 500 }] },
        { id: 'g9', kind: 'conduit', points: [{ x: 500, y: 460 }, { x: 780, y: 460 }, { x: 780, y: 400 }] },
        { id: 'g10', kind: 'conduit', points: [{ x: 780, y: 400 }, { x: 780, y: 150 }] },
        { id: 'g11', kind: 'conduit', points: [{ x: 780, y: 150 }, { x: 780, y: 40 }, { x: 570, y: 40 }] },
        { id: 'g12', kind: 'conduit', points: [{ x: 570, y: 40 }, { x: 570, y: 240 }] },
        { id: 'g13', kind: 'conduit', points: [{ x: 570, y: 40 }, { x: 620, y: 40 }, { x: 620, y: 20 }] },
        { id: 'g14', kind: 'conduit', points: [{ x: 620, y: 40 }, { x: 700, y: 40 }, { x: 700, y: 20 }] },
      ],
    },
  },
];

function getExampleData(id) {
  const e = EXAMPLES.find((x) => x.id === id);
  return e ? JSON.parse(JSON.stringify(e.data)) : null;
}
